// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxyLGoHxQfSLOtVWU5PPZG9W2ILO9kfjk',
    appId: '1:949084502977:web:5df9e6069458eba7488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    authDomain: 'flit-crud-cf324.firebaseapp.com',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMTaRsWZa2M7D7QcHhf3q9Jqc7JifXrU',
    appId: '1:949084502977:android:10a000ed68379751488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3MsFwqS2NY2dQQNgoZ7pp-cqDN6xwBUo',
    appId: '1:949084502977:ios:849534cc053f4874488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    storageBucket: 'flit-crud-cf324.appspot.com',
    androidClientId: '949084502977-du0mlaaubg896rgp5slasga49gnpfc3d.apps.googleusercontent.com',
    iosClientId: '949084502977-ufquvormbefjffrlmb2uaefr3fo7jkbb.apps.googleusercontent.com',
    iosBundleId: 'Cvsflutter.firebaseui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxyLGoHxQfSLOtVWU5PPZG9W2ILO9kfjk',
    appId: '1:949084502977:web:1b1ad3a88cb456c0488d40',
    messagingSenderId: '949084502977',
    projectId: 'flit-crud-cf324',
    authDomain: 'flit-crud-cf324.firebaseapp.com',
    storageBucket: 'flit-crud-cf324.appspot.com',
  );
}
